# Generated by Django 4.0.1 on 2022-01-05 19:56

import book_list.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.CharField(max_length=255, null=True, verbose_name='Author')),
                ('pub_date', models.DateField(null=True, verbose_name='Publication date')),
                ('pub_lang', models.CharField(max_length=255, null=True, verbose_name='Publication language')),
                ('isbn', models.CharField(max_length=13, validators=[book_list.models.validate_isbn], verbose_name='ISBN')),
                ('pages', models.IntegerField(null=True, verbose_name='Number of pages')),
                ('cover_link', models.CharField(max_length=255, null=True, verbose_name='Cover link')),
            ],
        ),
    ]
