# Generated by Django 4.0.1 on 2022-01-08 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('author', models.CharField(max_length=255, null=True, verbose_name='Author')),
                ('pub_date', models.CharField(max_length=10, null=True, verbose_name='Publication date')),
                ('pub_lang', models.CharField(max_length=255, null=True, verbose_name='Publication language')),
                ('pages', models.IntegerField(null=True, verbose_name='Number of pages')),
                ('cover_link', models.URLField(max_length=255, null=True, verbose_name='Cover link')),
            ],
        ),
        migrations.CreateModel(
            name='IsbnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn_type', models.CharField(max_length=255, null=True, verbose_name='type')),
                ('isbn_num', models.CharField(max_length=255, null=True, verbose_name='isbn')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_isbn', to='book_list.bookmodel')),
            ],
        ),
    ]
