# Generated by Django 4.0.1 on 2022-01-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='cover_link',
            field=models.URLField(max_length=255, null=True, verbose_name='Cover link'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='pub_date',
            field=models.CharField(max_length=10, null=True, verbose_name='Publication date'),
        ),
    ]
