# Generated by Django 4.0.1 on 2022-01-06 16:35

import book_list.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0002_alter_bookmodel_cover_link_alter_bookmodel_pub_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='isbn',
            field=models.CharField(max_length=50, validators=[book_list.models.validate_isbn], verbose_name='ISBN'),
        ),
    ]
