# Generated by Django 4.0.1 on 2022-01-18 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0002_bookmodel_self_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='large_cover',
            field=models.URLField(max_length=255, null=True, verbose_name='Large cover link'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='self_link',
            field=models.URLField(max_length=255, null=True, verbose_name='self link'),
        ),
    ]
