# Generated by Django 4.0.1 on 2022-01-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0004_alter_bookmodel_cover_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='cover_link',
            field=models.URLField(max_length=500, null=True, verbose_name='Cover link'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='large_cover',
            field=models.URLField(max_length=500, null=True, verbose_name='Large cover link'),
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='self_link',
            field=models.URLField(max_length=500, null=True, verbose_name='self link'),
        ),
    ]
