# Generated by Django 4.0.1 on 2022-01-07 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0005_alter_bookmodel_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='title',
            field=models.CharField(default=None, max_length=255, verbose_name='Title'),
        ),
    ]
