# Generated by Django 4.0.1 on 2022-01-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0007_alter_bookmodel_isbn_alter_bookmodel_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='isbn',
            field=models.CharField(default=None, max_length=255, verbose_name='ISBN'),
        ),
    ]
