# Generated by Django 4.0.1 on 2022-01-07 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0009_alter_bookmodel_isbn_alter_bookmodel_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmodel',
            name='isbn',
        ),
        migrations.CreateModel(
            name='IsbnModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=255, null=True, verbose_name='ISBN')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='isbn', to='book_list.bookmodel')),
            ],
        ),
    ]
