# Generated by Django 4.0.1 on 2022-01-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_list', '0010_remove_bookmodel_isbn_isbnmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='isbnmodel',
            name='isbn',
        ),
        migrations.AddField(
            model_name='isbnmodel',
            name='isbn_num',
            field=models.CharField(max_length=255, null=True, verbose_name='isbn'),
        ),
        migrations.AddField(
            model_name='isbnmodel',
            name='isbn_type',
            field=models.CharField(max_length=255, null=True, verbose_name='type'),
        ),
    ]
